imagePullSecret: acr-auth-secret

followerImage:
  repository: deterministicChatServicee.azurecr.io/follower-service
  tag: v1.2

dapr:
  enabled: true
  pubsubComponent: redis
  statestoreComponent: redis

followers:
  replicas: 3
  appIdPrefix: follower
  appPortStart: 8000
  daprAppPortStart: 3500
  daprConfig:
    pubsub: pubsub
    statestore: statestore
